In [177]:
import numpy as np

In [178]:
import pandas as pd

In [179]:
data=pd.read_csv(r'C:\Users\ASUS\Downloads\YEARLY_2023_CAAQMS_FINAL_UPLOAD_merged (1).csv',na_values='-')

In [180]:
data

CO     Ozone      NO2       SO2     PM2.5      PM10   AQI
0        NaN       NaN      NaN       NaN       NaN       NaN   NaN
1    0.75000  18.07000   6.7600   9.26000  43.96000  69.54000  73.0
2    0.74000  17.64000   6.6200   9.87000  44.08000  69.75000  73.0
3    1.03000  16.15000   6.7400   9.87000  39.21000  62.83000  65.0
4    1.17000  17.59000   7.1200  10.81000  41.75000  66.50000  70.0
..       ...       ...      ...       ...       ...       ...   ...
762  0.58008  27.21238  12.3866  14.20219  25.54167  56.20833  56.0
763  0.45510  22.82584  14.6582  14.38560  16.50000  34.66667  35.0
764  0.45719  27.07407  12.7963  13.44474  16.91667  35.45833  35.0
765  0.53634  26.34239  12.6594  14.42967  19.16667  40.91667  41.0
766  0.58789  18.22695  16.0060  13.16010  17.70833  37.50000  38.0

[767 rows x 7 columns]

In [181]:
data.isnull().sum()

CO       47
Ozone    40
NO2      40
SO2      40
PM2.5    45
PM10     44
AQI      43
dtype: int64

In [182]:
data.dropna(inplace=True)

In [183]:
data.isnull().sum()

CO       0
Ozone    0
NO2      0
SO2      0
PM2.5    0
PM10     0
AQI      0
dtype: int64

In [184]:
x=data[['CO','Ozone','NO2','SO2','PM2.5','PM10']]
y=data['AQI']

In [185]:
data.shape

(715, 7)

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [188]:
x_train.shape

(572, 6)

In [189]:
x_test.shape

(143, 6)

In [190]:
from sklearn.neighbors import KNeighborsRegressor

In [191]:
reg1=KNeighborsRegressor(n_neighbors=3)

In [192]:
reg1.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [193]:
y_pred=reg1.predict(x_test)

In [194]:
from sklearn.metrics import r2_score

In [195]:
r2_score(y_test,y_pred)

0.4326166861613835

In [196]:
from sklearn.metrics import mean_squared_error

In [197]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 18.8186453853994


In [198]:
from sklearn.tree import DecisionTreeRegressor

In [199]:
model=DecisionTreeRegressor()

In [200]:
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [201]:
y_pred=model.predict(x_test)

In [202]:
y_pred

array([ 48.,  21., 108.,  43.,  20.,  93.,  19.,  50.,  29.,  34.,  16.,
       114.,  56.,  33.,  47., 128.,  15.,  75.,  77.,  27.,  17.,  40.,
        14.,  26.,  32.,  15.,  33.,  27.,  20.,  69.,  33.,  33.,  25.,
        39.,  50.,  38.,  60.,  42.,  39.,  43.,  73.,  23.,  88., 133.,
        73., 113.,  29.,  32.,  19.,  26.,  78.,  31.,  26.,  27.,  69.,
        19.,  23.,  83.,  74.,  45.,  20.,  20.,  88.,  87.,  41.,  38.,
        13.,  39.,  25.,  19.,  73.,  72., 109.,  21.,  58.,  61.,  31.,
        23.,  20.,  94.,  73., 106.,  19.,  46.,  72.,  47.,  21.,  65.,
        24.,  36.,  61.,  19.,  23.,  25.,  88.,  27.,  19.,  34.,  32.,
        77.,  28., 113.,  72.,  56.,  30.,  39.,  41.,  42.,  70.,  19.,
        22.,  32.,  50.,  77.,  21.,  38.,  20.,  41.,  42.,  52., 103.,
        30.,  23.,  16.,  20.,  77.,  93.,  64.,  27.,  33.,  23.,  54.,
        30.,  25.,  50.,  35.,  77.,  23.,  41.,  30.,  17.,  64.,  35.])

In [203]:
from sklearn.metrics import r2_score

In [204]:
r2_score(y_test,y_pred)

0.46373201796487684

In [205]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 18.29536224621638


In [206]:
from sklearn.ensemble import RandomForestRegressor
reg2=RandomForestRegressor(n_estimators=100,random_state=0)
reg2.fit(x_train,y_train)


RandomForestRegressor(random_state=0)

In [207]:
y_pred=reg2.predict(x_test)

In [208]:
y_pred

array([ 59.46,  45.12,  81.33,  56.7 ,  20.93,  73.33,  20.38,  47.12,
        27.15,  36.23,  17.04,  85.5 ,  66.69,  34.8 ,  50.57,  87.67,
        14.84,  58.22,  62.53,  33.08,  17.28,  37.3 ,  13.68,  30.34,
        37.67,  15.48,  34.71,  32.34,  22.71,  50.54,  32.21,  33.06,
        35.69,  40.15,  41.82,  34.25,  52.38,  36.85,  49.11,  44.86,
        37.47,  25.9 ,  95.38, 113.55,  34.2 , 100.79,  36.97,  33.01,
        24.46,  27.05,  19.92,  29.34,  26.97,  38.13,  57.89,  22.34,
        23.01,  94.03,  72.89,  45.08,  18.42,  26.08,  97.89,  90.56,
        41.76,  40.53,  13.35,  40.48,  26.04,  21.41,  38.1 ,  52.13,
       110.32,  39.89,  60.83,  62.66,  32.49,  26.82,  21.36,  56.91,
        47.6 ,  87.91,  20.15,  36.17,  77.85,  47.5 ,  33.54,  90.1 ,
        37.8 ,  38.02,  62.18,  39.84,  25.18,  25.74,  89.96,  24.41,
        19.61,  34.89,  33.52,  60.85,  27.94, 110.28,  72.55,  56.64,
        33.4 ,  38.3 ,  42.77,  43.87,  66.71,  29.96,  21.93,  40.19,
      

In [209]:
from sklearn.metrics import r2_score

In [210]:
r2_score(y_test,y_pred)

0.655263181333564

In [211]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 14.668777245364586


In [212]:
from sklearn.linear_model import LinearRegression

In [213]:
reg3=LinearRegression()

In [215]:
reg3.fit(x_train,y_train)

LinearRegression()

In [216]:
y_pred=reg3.predict(x_test)

In [217]:
y_pred

array([ 57.36555491,  40.20647307,  76.04825897,  67.7840999 ,
        22.37445262,  42.31970821,  27.38713237,  38.54508973,
        33.96148185,  29.07563614,  22.58798127,  73.57882265,
        41.8932105 ,  42.10590639,  59.7778793 ,  75.91104308,
        19.84659416,  36.93956457,  65.63383271,  34.40593063,
        22.38235964,  30.17467677,  20.66608215,  31.1607013 ,
        45.27855101,  17.40914376,  41.54373187,  26.27411817,
        28.58325091,  31.90139689,  33.89544311,  38.08261719,
        30.05387133,  49.86659875,  40.41275942,  35.74644539,
        56.8543818 ,  42.92450496,  49.5479404 ,  28.27885688,
        26.21924303,  32.55114695,  95.78595186, 115.10232456,
        35.08002889,  94.10191918,  37.10097873,  35.54464608,
        28.05197157,  26.40863756,  25.08712081,  27.13469495,
        31.24687229,  32.11522704,  33.48990041,  27.25887806,
        29.55370742,  90.56043133,  45.75001826,  55.7438487 ,
        22.60507564,  26.93381105,  98.8220463 ,  99.97

In [218]:
from sklearn.metrics import r2_score

In [219]:
r2_score(y_test,y_pred)

0.5340117365219305

In [220]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 17.05444410905868


In [223]:
import pickle
file=open("finalmodel.pkl","wb")
pickle.dump(reg2,file)
file.close()